### ISSUE TITLE
Nemojte da dozvolite da korisnik trazi zmiji da ide unatraske

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG17/RG109-zmijica#4]
Sadasnja implementacija ubija program ako korisnik pokusa da trazi zmiji da se krece suprotno njenom trenutnom pravcu (na primer, ako se zmija krece nadesno, a korisnik pritisne 'a'). Umesto kraja programa, samo ignorisite ove zahteve korisnika.

**Comment by mi15247** [comment]
Odradjeno.
